name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Homebrew (if needed)
        run: |
          which -s brew
          if [[ $? != 0 ]]; then
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          fi

      - name: Install dependencies
        run: brew install openssl

      - name: Build
        run: make all
        
      - name: Upload choma_cli
        uses: actions/upload-artifact@v3.1.0
        with:
          name: choma_cli
          path: ${{ github.workspace }}/output/tests/choma_cli
      
      - name: Upload ct_bypass
        uses: actions/upload-artifact@v3.1.0
        with:
          name: choma_cli
          path: ${{ github.workspace }}/output/tests/ct_bypass
