name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Homebrew (if needed)
        run: |
          which -s brew
          if [[ $? != 0 ]]; then
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          fi

      - name: Install dependencies
        run: brew install openssl

      - name: Build
        run: make all
        
      - name: Git Push
        run: |
            cp ./output/choma_cli choma_cli
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add choma_cli
            git commit -m "Built ChOma"
            git push
